// Code generated by soft.generator.go. DO NOT EDIT.

package ecore

// EAnnotation is the representation of the model object 'EAnnotation'
type EAnnotation interface {
	EModelElement

	GetSource() string
	SetSource(string)

	GetDetails() EMap[string, string]

	GetEModelElement() EModelElement
	SetEModelElement(EModelElement)

	GetContents() EList[EObject]

	GetReferences() EList[EObject]

	// Start of user code EAnnotation
	// End of user code
}
