// Code generated by soft.generator.go. DO NOT EDIT.

package ecore

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func discardMockEAttribute() {
	_ = assert.Equal
	_ = testing.Coverage
}

// TestMockEAttributeGetEAttributeType tests method GetEAttributeType
func TestMockEAttributeGetEAttributeType(t *testing.T) {
	o := &MockEAttribute{}
	r := &MockEDataType{}
	o.On("GetEAttributeType").Once().Return(r)
	o.On("GetEAttributeType").Once().Return(func() EDataType {
		return r
	})
	assert.Equal(t, r, o.GetEAttributeType())
	assert.Equal(t, r, o.GetEAttributeType())
	o.AssertExpectations(t)
}

// TestMockEAttributeIsID tests method IsID
func TestMockEAttributeIsID(t *testing.T) {
	o := &MockEAttribute{}
	r := true
	o.On("IsID").Once().Return(r)
	o.On("IsID").Once().Return(func() bool {
		return r
	})
	assert.Equal(t, r, o.IsID())
	assert.Equal(t, r, o.IsID())
	o.AssertExpectations(t)
}

// TestMockEAttributeSetID tests method SetID
func TestMockEAttributeSetID(t *testing.T) {
	o := &MockEAttribute{}
	v := true
	o.On("SetID", v).Once()
	o.SetID(v)
	o.AssertExpectations(t)
}
