// Code generated by soft.generator.go. DO NOT EDIT.



package ecore



// EAttribute is the representation of the model object 'EAttribute'
type EAttribute interface {
    EStructuralFeature

    IsID() bool
    SetID( bool )
    
    
    GetEAttributeType() EDataType
    
    
    // Start of user code EAttribute
    // End of user code
}

