// Code generated by soft.generator.go. DO NOT EDIT.

package ecore

import "reflect"

// EClassifier is the representation of the model object 'EClassifier'
type EClassifier interface {
	ENamedElement

	IsInstance(any) bool

	GetInstanceTypeName() string
	SetInstanceTypeName(string)

	GetInstanceClass() reflect.Type
	SetInstanceClass(reflect.Type)

	GetDefaultValue() any

	GetClassifierID() int
	SetClassifierID(int)

	GetEPackage() EPackage

	// Start of user code EClassifier
	// End of user code
}
