// Code generated by soft.generator.go. DO NOT EDIT.

package ecore

// EDataType is the representation of the model object 'EDataType'
type EDataType interface {
	EClassifier

	IsSerializable() bool
	SetSerializable(bool)

	// Start of user code EDataType
	// End of user code
}
