// Code generated by soft.generator.go. DO NOT EDIT.

package ecore

type MockEDataType struct {
	MockEClassifier
}

// IsSerializable get the value of isSerializable
func (eDataType *MockEDataType) IsSerializable() bool {
	ret := eDataType.Called()

	var r bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r = rf()
	} else {
		if ret.Get(0) != nil {
			r = ret.Get(0).(bool)
		}
	}

	return r
}

// SetSerializable provides mock implementation for setting the value of isSerializable
func (eDataType *MockEDataType) SetSerializable(newIsSerializable bool) {
	eDataType.Called(newIsSerializable)
}
