// Code generated by soft.generator.go. DO NOT EDIT.

package ecore

// EEnum is the representation of the model object 'EEnum'
type EEnum interface {
	EDataType

	GetEEnumLiteralByName(string) EEnumLiteral
	GetEEnumLiteralByValue(int) EEnumLiteral
	GetEEnumLiteralByLiteral(string) EEnumLiteral

	GetELiterals() EList[EEnumLiteral]

	// Start of user code EEnum
	// End of user code
}
