// Code generated by soft.generator.go. DO NOT EDIT.

package ecore

// EEnumLiteral is the representation of the model object 'EEnumLiteral'
type EEnumLiteral interface {
	ENamedElement

	GetValue() int
	SetValue(int)

	GetInstance() any
	SetInstance(any)

	GetLiteral() string
	SetLiteral(string)

	GetEEnum() EEnum

	// Start of user code EEnumLiteral
	// End of user code
}
