// Code generated by soft.generator.go. DO NOT EDIT.

package ecore

type MockEFactory struct {
	MockEModelElement
}

// GetEPackage get the value of ePackage
func (eFactory *MockEFactory) GetEPackage() EPackage {
	ret := eFactory.Called()

	var r EPackage
	if rf, ok := ret.Get(0).(func() EPackage); ok {
		r = rf()
	} else {
		if ret.Get(0) != nil {
			r = ret.Get(0).(EPackage)
		}
	}

	return r
}

// SetEPackage provides mock implementation for setting the value of ePackage
func (eFactory *MockEFactory) SetEPackage(newEPackage EPackage) {
	eFactory.Called(newEPackage)
}

// ConvertToString provides mock implementation
func (eFactory *MockEFactory) ConvertToString(eDataType EDataType, instanceValue any) string {
	ret := eFactory.Called(eDataType, instanceValue)

	var r string
	if rf, ok := ret.Get(0).(func() string); ok {
		r = rf()
	} else {
		if ret.Get(0) != nil {
			r = ret.Get(0).(string)
		}
	}

	return r
}

// Create provides mock implementation
func (eFactory *MockEFactory) Create(eClass EClass) EObject {
	ret := eFactory.Called(eClass)

	var r EObject
	if rf, ok := ret.Get(0).(func() EObject); ok {
		r = rf()
	} else {
		if ret.Get(0) != nil {
			r = ret.Get(0).(EObject)
		}
	}

	return r
}

// CreateFromString provides mock implementation
func (eFactory *MockEFactory) CreateFromString(eDataType EDataType, literalValue string) any {
	ret := eFactory.Called(eDataType, literalValue)

	var r any
	if rf, ok := ret.Get(0).(func() any); ok {
		r = rf()
	} else {
		if ret.Get(0) != nil {
			r = ret.Get(0).(any)
		}
	}

	return r
}
