// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2021 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

package ecore

type MockEList[T any] struct {
	MockECollection[T]
}

// Get provides a mock function with given fields: _a0
func (_m *MockEList[T]) Get(_a0 int) T {
	ret := _m.Called(_a0)

	var r0 T
	if rf, ok := ret.Get(0).(func(int) T); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	return r0
}

// IndexOf provides a mock function with given fields: _a0
func (_m *MockEList[T]) IndexOf(_a0 T) int {
	ret := _m.Called(_a0)

	var r0 int
	if rf, ok := ret.Get(0).(func(T) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Insert provides a mock function with given fields: _a0, _a1
func (_m *MockEList[T]) Insert(_a0 int, _a1 T) bool {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, T) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// InsertAll provides a mock function with given fields: _a0, _a1
func (_m *MockEList[T]) InsertAll(_a0 int, _a1 ECollection[T]) bool {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, ECollection[T]) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Move provides a mock function with given fields: _a0, _a1
func (_m *MockEList[T]) MoveIndex(_a0 int, _a1 int) T {
	ret := _m.Called(_a0, _a1)

	var r0 T
	if rf, ok := ret.Get(0).(func(int, int) T); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	return r0
}

// MoveObject provides a mock function with given fields: _a0, _a1
func (_m *MockEList[T]) MoveObject(_a0 int, _a1 T) {
	_m.Called(_a0, _a1)
}

// RemoveAt provides a mock function with given fields: _a0
func (_m *MockEList[T]) RemoveAt(_a0 int) T {
	ret := _m.Called(_a0)

	var r0 T
	if rf, ok := ret.Get(0).(func(int) T); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	return r0
}

// Set provides a mock function with given fields: _a0, _a1
func (_m *MockEList[T]) Set(_a0 int, _a1 T) T {
	ret := _m.Called(_a0, _a1)

	var r0 T
	if rf, ok := ret.Get(0).(func(int, T) T); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	return r0
}
