// Code generated by soft.generator.go. DO NOT EDIT.



package ecore



// EModelElement is the representation of the model object 'EModelElement'
type EModelElement interface {
    EObject

    GetEAnnotation(string) EAnnotation
    
    GetEAnnotations() EList[EAnnotation]
    
    
    // Start of user code EModelElement
    // End of user code
}

