// Code generated by soft.generator.go. DO NOT EDIT.



package ecore


type MockEModelElement struct {
	MockEObjectInternal
}

// GetEAnnotations get the value of eAnnotations
func (eModelElement *MockEModelElement) GetEAnnotations() EList[EAnnotation] {
	ret := eModelElement.Called()

	var r EList[EAnnotation]
	if rf, ok := ret.Get(0).(func() EList[EAnnotation]); ok {
		r = rf()
	} else {
		if ret.Get(0) != nil {
			r = ret.Get(0).(EList[EAnnotation])
		}
	}

	return r
}


// GetEAnnotation provides mock implementation
func (eModelElement *MockEModelElement) GetEAnnotation(source string) EAnnotation {
	ret := eModelElement.Called(source)

	var r EAnnotation
	if rf, ok := ret.Get(0).(func() EAnnotation); ok {
		r = rf()
	} else {
		if ret.Get(0) != nil {
			r = ret.Get(0).(EAnnotation)
		}
	}

	return r
}



