// Code generated by soft.generator.go. DO NOT EDIT.

package ecore

// ENamedElement is the representation of the model object 'ENamedElement'
type ENamedElement interface {
	EModelElement

	GetName() string
	SetName(string)

	// Start of user code ENamedElement
	// End of user code
}
