// Code generated by soft.generator.go. DO NOT EDIT.

package ecore

// EObject is the representation of the model object 'EObject'
type EObject interface {
	ENotifier

	EClass() EClass
	EIsProxy() bool
	EResource() EResource
	EContainer() EObject
	EContainingFeature() EStructuralFeature
	EContainmentFeature() EReference
	EContents() EList[EObject]
	EAllContents() EIterator[EObject]
	ECrossReferences() EList[EObject]
	EGet(EStructuralFeature) any
	EGetResolve(EStructuralFeature, bool) any
	ESet(EStructuralFeature, any)
	EIsSet(EStructuralFeature) bool
	EUnset(EStructuralFeature)
	EInvoke(EOperation, EList[any]) any

	// Start of user code EObject
	// End of user code
}
