// Code generated by soft.generator.go. DO NOT EDIT.

package ecore

import (
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"testing"
)

func discardEObject() {
	_ = assert.Equal
	_ = mock.Anything
	_ = testing.Coverage
}

func TestEObjectAsEObject(t *testing.T) {
	o := NewEObjectImpl()
	assert.Equal(t, o, o.asEObject())
}

func TestEObjectStaticClass(t *testing.T) {
	o := NewEObjectImpl()
	assert.Equal(t, GetPackage().GetEObject(), o.EStaticClass())
}

func TestEObjectFeatureCount(t *testing.T) {
	o := NewEObjectImpl()
	assert.Equal(t, EOBJECT_FEATURE_COUNT, o.EStaticFeatureCount())
}
