// Code generated by soft.generator.go. DO NOT EDIT.

package ecore

// EOperation is the representation of the model object 'EOperation'
type EOperation interface {
	ETypedElement

	IsOverrideOf(EOperation) bool

	GetOperationID() int
	SetOperationID(int)

	GetEContainingClass() EClass

	GetEParameters() EList[EParameter]

	GetEExceptions() EList[EClassifier]
	UnsetEExceptions()

	// Start of user code EOperation
	// End of user code
}
