// Code generated by soft.generator.go. DO NOT EDIT.

package ecore

// EPackage is the representation of the model object 'EPackage'
type EPackage interface {
	ENamedElement

	GetEClassifier(string) EClassifier

	GetNsURI() string
	SetNsURI(string)

	GetNsPrefix() string
	SetNsPrefix(string)

	GetEFactoryInstance() EFactory
	SetEFactoryInstance(EFactory)

	GetEClassifiers() EList[EClassifier]

	GetESubPackages() EList[EPackage]

	GetESuperPackage() EPackage

	// Start of user code EPackage
	// End of user code
}
