// Code generated by soft.generator.go. DO NOT EDIT.

package ecore

// EParameter is the representation of the model object 'EParameter'
type EParameter interface {
	ETypedElement

	GetEOperation() EOperation

	// Start of user code EParameter
	// End of user code
}
