// Code generated by soft.generator.go. DO NOT EDIT.



package ecore

import (
	"testing"
	"github.com/stretchr/testify/assert"
)

func discardMockEParameter() {
	_ = assert.Equal
	_ = testing.Coverage
}

// TestMockEParameterGetEOperation tests method GetEOperation
func TestMockEParameterGetEOperation(t *testing.T) {
	o := &MockEParameter{}
	r := &MockEOperation{}
	o.On("GetEOperation").Once().Return(r)
	o.On("GetEOperation").Once().Return( func () EOperation {
		return r
	})
	assert.Equal(t,r,o.GetEOperation())
	assert.Equal(t,r,o.GetEOperation())
	o.AssertExpectations(t)
}




