// Code generated by soft.generator.go. DO NOT EDIT.



package ecore



// EReference is the representation of the model object 'EReference'
type EReference interface {
    EStructuralFeature

    IsContainment() bool
    SetContainment( bool )
    
    IsContainer() bool
    
    IsResolveProxies() bool
    SetResolveProxies( bool )
    
    
    GetEOpposite() EReference
    SetEOpposite( EReference )
    
    GetEReferenceType() EClass
    
    GetEKeys() EList[EAttribute]
    
    
    // Start of user code EReference
    // End of user code
}

