// Code generated by soft.generator.go. DO NOT EDIT.



package ecore

import (
	"testing"
	"github.com/stretchr/testify/assert"
)

func discardMockEStringToStringMapEntry() {
	_ = assert.Equal
	_ = testing.Coverage
}

// TestMockEStringToStringMapEntryGetKey tests method GetKey
func TestMockEStringToStringMapEntryGetKey(t *testing.T) {
	o := &MockEStringToStringMapEntry{}
	r := "Test String"
	o.On("GetKey").Once().Return(r)
	o.On("GetKey").Once().Return( func () string {
		return r
	})
	assert.Equal(t,r,o.GetKey())
	assert.Equal(t,r,o.GetKey())
	o.AssertExpectations(t)
}

// TestMockEStringToStringMapEntrySetKey tests method SetKey
func TestMockEStringToStringMapEntrySetKey(t *testing.T) {
	o := &MockEStringToStringMapEntry{}
	v := "Test String"
	o.On("SetKey",v).Once()
	o.SetKey(v)
	o.AssertExpectations(t)
}

// TestMockEStringToStringMapEntryGetValue tests method GetValue
func TestMockEStringToStringMapEntryGetValue(t *testing.T) {
	o := &MockEStringToStringMapEntry{}
	r := "Test String"
	o.On("GetValue").Once().Return(r)
	o.On("GetValue").Once().Return( func () string {
		return r
	})
	assert.Equal(t,r,o.GetValue())
	assert.Equal(t,r,o.GetValue())
	o.AssertExpectations(t)
}

// TestMockEStringToStringMapEntrySetValue tests method SetValue
func TestMockEStringToStringMapEntrySetValue(t *testing.T) {
	o := &MockEStringToStringMapEntry{}
	v := "Test String"
	o.On("SetValue",v).Once()
	o.SetValue(v)
	o.AssertExpectations(t)
}




