// Code generated by soft.generator.go. DO NOT EDIT.

package ecore

// EStringToStringMapEntry is the representation of the model object 'EStringToStringMapEntry'
type EStringToStringMapEntry interface {
	EObject
	EMapEntry

	GetStringKey() string
	SetStringKey(string)

	GetStringValue() string
	SetStringValue(string)

	// Start of user code EStringToStringMapEntry
	// End of user code
}
