// Code generated by soft.generator.go. DO NOT EDIT.



package ecore



// EStringToStringMapEntry is the representation of the model object 'EStringToStringMapEntry'
type EStringToStringMapEntry interface {
    EMapEntry[string,string]

    GetKey() string
    SetKey( string )
    
    GetValue() string
    SetValue( string )
    
    
    // Start of user code EStringToStringMapEntry
    // End of user code
}

