// Code generated by soft.generator.go. DO NOT EDIT.



package ecore

import (
	"testing"
	"github.com/stretchr/testify/assert"
)

func discardMockETypeParameter() {
	_ = assert.Equal
	_ = testing.Coverage
}

// TestMockETypeParameterGetEBounds tests method GetEBounds
func TestMockETypeParameterGetEBounds(t *testing.T) {
	o := &MockETypeParameter{}
	l := &MockEList[EGenericType]{}
	// return a value
	o.On("GetEBounds").Once().Return(l)
	o.On("GetEBounds").Once().Return( func () EList[EGenericType] {
		return l
	})	
	assert.Equal(t,l,o.GetEBounds())
	assert.Equal(t,l,o.GetEBounds())
	o.AssertExpectations(t)
}




