// Code generated by soft.generator.go. DO NOT EDIT.

package ecore

// ETypeParameter is the representation of the model object 'ETypeParameter'
type ETypeParameter interface {
	ENamedElement

	GetEBounds() EList[EGenericType]

	// Start of user code ETypeParameter
	// End of user code
}
