// Code generated by soft.generator.go. DO NOT EDIT.



package ecore


type MockETypeParameter struct {
	MockENamedElement
}

// GetEBounds get the value of eBounds
func (eTypeParameter *MockETypeParameter) GetEBounds() EList[EGenericType] {
	ret := eTypeParameter.Called()

	var r EList[EGenericType]
	if rf, ok := ret.Get(0).(func() EList[EGenericType]); ok {
		r = rf()
	} else {
		if ret.Get(0) != nil {
			r = ret.Get(0).(EList[EGenericType])
		}
	}

	return r
}




