// Code generated by mockery v2.15.0. DO NOT EDIT.

package diff

import mock "github.com/stretchr/testify/mock"

// MockDiffVisitor is an autogenerated mock type for the DiffVisitor type
type MockDiffVisitor[T interface{}] struct {
	mock.Mock
}

// HandleAdd provides a mock function with given fields: index, element
func (_m *MockDiffVisitor[T]) HandleAdd(index int, element T) {
	_m.Called(index, element)
}

// HandleMove provides a mock function with given fields: oldIndex, newIndex, element
func (_m *MockDiffVisitor[T]) HandleMove(oldIndex int, newIndex int, element T) {
	_m.Called(oldIndex, newIndex, element)
}

// HandleRemove provides a mock function with given fields: index, element
func (_m *MockDiffVisitor[T]) HandleRemove(index int, element T) {
	_m.Called(index, element)
}

// HandleReplace provides a mock function with given fields: index, oldElement, newElement
func (_m *MockDiffVisitor[T]) HandleReplace(index int, oldElement T, newElement T) {
	_m.Called(index, oldElement, newElement)
}

type mockConstructorTestingTNewMockDiffVisitor interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDiffVisitor creates a new instance of MockDiffVisitor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDiffVisitor[T interface{}](t mockConstructorTestingTNewMockDiffVisitor) *MockDiffVisitor[T] {
	mock := &MockDiffVisitor[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
