// Code generated by mockery v2.15.0. DO NOT EDIT.

package diff

import mock "github.com/stretchr/testify/mock"

// MockVisitor is an autogenerated mock type for the Visitor type
type MockVisitor[T interface{}] struct {
	mock.Mock
}

// HandleAdd provides a mock function with given fields: index, element
func (_m *MockVisitor[T]) HandleAdd(index int, element T) {
	_m.Called(index, element)
}

// HandleMove provides a mock function with given fields: oldIndex, newIndex, element
func (_m *MockVisitor[T]) HandleMove(oldIndex int, newIndex int, element T) {
	_m.Called(oldIndex, newIndex, element)
}

// HandleRemove provides a mock function with given fields: index, element
func (_m *MockVisitor[T]) HandleRemove(index int, element T) {
	_m.Called(index, element)
}

// HandleReplace provides a mock function with given fields: index, oldElement, newElement
func (_m *MockVisitor[T]) HandleReplace(index int, oldElement T, newElement T) {
	_m.Called(index, oldElement, newElement)
}

type mockConstructorTestingTNewMockVisitor interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockVisitor creates a new instance of MockVisitor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockVisitor[T interface{}](t mockConstructorTestingTNewMockVisitor) *MockVisitor[T] {
	mock := &MockVisitor[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
