// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2021 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

package ecore

import mock "github.com/stretchr/testify/mock"

// MockEDynamicProperties is an autogenerated mock type for the EObjectProperties type
type MockEDynamicProperties struct {
	mock.Mock
}

// EDynamicGet provides a mock function with given fields: dynamicFeatureID
func (_m *MockEDynamicProperties) EDynamicGet(dynamicFeatureID int) interface{} {
	ret := _m.Called(dynamicFeatureID)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(int) interface{}); ok {
		r0 = rf(dynamicFeatureID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// EDynamicSet provides a mock function with given fields: dynamicFeatureID, newValue
func (_m *MockEDynamicProperties) EDynamicSet(dynamicFeatureID int, newValue interface{}) {
	_m.Called(dynamicFeatureID, newValue)
}

// EDynamicUnset provides a mock function with given fields: dynamicFeatureID
func (_m *MockEDynamicProperties) EDynamicUnset(dynamicFeatureID int) {
	_m.Called(dynamicFeatureID)
}
