// Code generated by soft.generator.go. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2021 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

package ecore

type MockETypeParameter struct {
	MockENamedElement
}

// GetEBounds get the value of eBounds
func (eTypeParameter *MockETypeParameter) GetEBounds() EList[EGenericType] {
	ret := eTypeParameter.Called()

	var r EList[EGenericType]
	if rf, ok := ret.Get(0).(func() EList[EGenericType]); ok {
		r = rf()
	} else {
		if ret.Get(0) != nil {
			r = ret.Get(0).(EList[EGenericType])
		}
	}

	return r
}
