name: Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout Go
      uses: actions/checkout@v2
      with:
        path: go
    - name: Checkout Models
      uses: actions/checkout@v2
      with:
        repository: masagroup/soft.models
        ref: f487e7c84891f31791cd55adb43d30345c99a9f1
        path: models
    - name: Build And Test
      working-directory: go
      run: make generate build test
